updated app validation

diff --git a/.github/workflows/Build_Scan_Deploy.yml b/.github/workflows/Build_Scan_Deploy.yml
--- a/.github/workflows/Build_Scan_Deploy.yml
+++ b/.github/workflows/Build_Scan_Deploy.yml
@@ -284,66 +284,37 @@ jobs:
 
           echo ""
           echo "4. Starting Prometheus port-forward..."
-
           kubectl port-forward \
             svc/monitoring-kube-prometheus-prometheus \
             -n monitoring \
             9090:9090 >/tmp/prometheus.log 2>&1 &
 
+          sleep 20
+
           echo "Waiting for Prometheus API..."
-
-          for i in {1..30}; do
-
-            if curl -sf http://localhost:9090/-/ready >/dev/null; then
-              echo "Prometheus is ready."
-              break
-            fi
-
-            sleep 2
-
-          done
-
-          echo ""
-          echo "5. Waiting for hello-gke target..."
-
-          for i in {1..30}; do
-
-            RESULT=$(curl -s \
-            "http://localhost:9090/api/v1/query?query=up{job=\"hello-gke\"}")
-
-            echo "$RESULT"
-
-            if echo "$RESULT" | grep '"value"' >/dev/null &&
-              echo "$RESULT" | grep '"1"' >/dev/null; then
-
-              echo "hello-gke target is UP."
-              break
-
-            fi
-
-            echo "Target not ready yet..."
+          until curl -s http://localhost:9090/-/ready >/dev/null; do
             sleep 5
-
-            if [ $i -eq 30 ]; then
-              echo "ERROR: hello-gke target never became UP."
-              exit 1
-            fi
-
           done
 
-          echo ""
-          echo "6. Verifying JVM metrics..."
-
-          curl -s \
-            "http://localhost:9090/api/v1/query?query=jvm_memory_used_bytes" \
-            | grep jvm_memory_used_bytes
+          echo "Prometheus is ready."
 
           echo ""
-          echo "7. Verifying HTTP metrics..."
+          echo "5. Verifying JVM Metrics..."
 
-          curl -s \
-            "http://localhost:9090/api/v1/query?query=http_server_requests_seconds_count" \
-            | grep http_server_requests_seconds_count
+          curl -sG \
+            --data-urlencode 'query=jvm_memory_used_bytes' \
+            http://localhost:9090/api/v1/query \
+            | grep "jvm_memory_used_bytes" \
+            || (echo "ERROR: JVM metrics not found"; exit 1)
+
+          echo ""
+          echo "6. Verifying HTTP Metrics..."
+
+          curl -sG \
+            --data-urlencode 'query=http_server_requests_seconds_count' \
+            http://localhost:9090/api/v1/query \
+            | grep "http_server_requests_seconds_count" \
+            || (echo "ERROR: HTTP metrics not found"; exit 1)
 
           pkill -f "kubectl port-forward" || true
 
